services:
  selenium-hub:
    image: selenium/hub:4.32.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:133.0.6943.141-chromedriver-133.0.6943.141-grid-4.32.0-20250505
    platform: linux/amd64
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_START_XVFB=true
      - SE_START_VNC=false
      - SE_START_NO_VNC=false
